from django.urls import path

from .views import (
    AsociacionesSectorPendientesView,
    CargoDetailView,
    CargoListCreateView,
    JuntaVecinosDetailView,
    JuntaVecinosListCreateView,
    ResolverAsociacionSectorView,
    SectorDetailView,
    SectorListCreateView,
    SectoresDisponiblesView,
    SolicitarAsociacionSectorView,
    DirectivaDetailView,
    DirectivaListCreateView,
    IntegranteDirectivaListCreateView,
    IntegranteDirectivaDetailView,
    UsuariosElegiblesDirectivaView,
)

urlpatterns = [
    path(
        "resolver-asociacion-sector/<int:usuario_id>/",
        ResolverAsociacionSectorView.as_view(),
        name="resolver-asociacion-sector",
    ),
    path(
        "asociaciones-pendientes/",
        AsociacionesSectorPendientesView.as_view(),
        name="asociaciones-sector-pendientes",
    ),
    path(
        "solicitar-asociacion-sector/",
        SolicitarAsociacionSectorView.as_view(),
        name="solicitar-asociacion-sector",
    ),
    path(
        "sectores-disponibles/",
        SectoresDisponiblesView.as_view(),
        name="sectores-disponibles",
    ),
    path(
        "juntas/",
        JuntaVecinosListCreateView.as_view(),
        name="juntas-list-create",
    ),
    path(
        "juntas/<int:pk>/",
        JuntaVecinosDetailView.as_view(),
        name="juntas-detail",
    ),
    path(
        "sectores/",
        SectorListCreateView.as_view(),
        name="sectores-list-create",
    ),
    path(
        "sectores/<int:pk>/",
        SectorDetailView.as_view(),
        name="sectores-detail",
    ),
    path(
        "cargos/",
        CargoListCreateView.as_view(),
        name="cargos-list-create",
    ),
    path(
        "cargos/<int:pk>/",
        CargoDetailView.as_view(),
        name="cargos-detail",
    ),
    path(
        "directivas/",
        DirectivaListCreateView.as_view(),
        name="directivas-list-create",
    ),
    path(
        "directivas/<int:pk>/",
        DirectivaDetailView.as_view(),
        name="directivas-detail",
    ),
    path(
        "integrantes-directiva/",
        IntegranteDirectivaListCreateView.as_view(),
        name="integrantes-directiva-list-create",
    ),
    path(
        "integrantes-directiva/<int:pk>/",
        IntegranteDirectivaDetailView.as_view(),
        name="integrantes-directiva-detail",
    ),
    path(
        "directivas/<int:directiva_id>/usuarios-elegibles/",
        UsuariosElegiblesDirectivaView.as_view(),
        name="usuarios-elegibles-directiva",
    ),
]
