# Generated by Django 5.2.17 on 2026-09-12 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('permite_multiples', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Directiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('FINALIZADA', 'Finalizada')], default='VIGENTE', max_length=20)),
                ('observacion', models.CharField(blank=True, max_length=500, null=True)),
                ('junta_vecinos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='directivas', to='organizacion.juntavecinos')),
            ],
        ),
        migrations.CreateModel(
            name='IntegranteDirectiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integrantes', to='organizacion.cargo')),
                ('directiva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integrantes', to='organizacion.directiva')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integraciones_directiva', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
