# Generated by Django 5.2.17 on 2026-10-02 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0003_directiva_ck_directiva_fechas_validas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificacionResidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('ELECTRICIDAD', 'Boleta de electricidad'), ('AGUA', 'Boleta de agua'), ('GAS', 'Boleta de gas'), ('INTERNET', 'Boleta de internet')], max_length=20)),
                ('archivo', models.FileField(upload_to='verificaciones_residencia/')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VALIDADA', 'Validada'), ('REVISION_MANUAL', 'Revisión manual'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('nombre_extraido', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion_extraida', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_documento_extraida', models.DateField(blank=True, null=True)),
                ('confianza_ocr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('observacion_automatica', models.TextField(blank=True, null=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verificaciones_residencia_revisadas', to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verificaciones_residencia', to='organizacion.sector')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verificaciones_residencia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion', '-id'],
            },
        ),
    ]
