# Generated by Django 5.2.17 on 2026-10-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0004_verificacionresidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificacionresidencia',
            name='comuna_extraida',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
