# Generated by Django 5.2.17 on 2026-10-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0005_verificacionresidencia_comuna_extraida'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificacionresidencia',
            name='hash_archivo',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
