# Generated by Django 5.2.17 on 2026-10-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0006_verificacionresidencia_hash_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificacionresidencia',
            name='documento_duplicado',
            field=models.BooleanField(default=False),
        ),
    ]
