# Generated by Django 5.2.17 on 2026-09-25 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacion', '0003_directiva_ck_directiva_fechas_validas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publicaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('directiva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publicaciones', to='organizacion.directiva')),
            ],
            options={
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
