# Generated by Django 5.2.17 on 2026-09-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicaciones', '0004_conversacion_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='rol_remitente',
            field=models.CharField(blank=True, choices=[('VECINO', 'Vecino'), ('DIRECTIVA', 'Directiva')], max_length=20, null=True),
        ),
    ]
