# Generated by Django 5.2.17 on 2026-09-28 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacion', '0003_directiva_ck_directiva_fechas_validas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudVecino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CONSULTA', 'Consulta'), ('RECLAMO', 'Reclamo'), ('SOLICITUD', 'Solicitud')], max_length=20)),
                ('asunto', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('RESPONDIDA', 'Respondida'), ('CERRADA', 'Cerrada')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('junta_vecinos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_vecino', to='organizacion.juntavecinos')),
                ('vecino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_vecino', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
