# Generated by Django 5.2.17 on 2026-09-28 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudvecino',
            name='fecha_respuesta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudvecino',
            name='respondido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_respondidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudvecino',
            name='respuesta',
            field=models.TextField(blank=True, default=''),
        ),
    ]
