# Generated by Django 5.2.17 on 2026-09-28 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0003_directiva_ck_directiva_fechas_validas_and_more'),
        ('solicitudes', '0003_tipodocumento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_seguimiento', models.CharField(max_length=30, unique=True)),
                ('motivo', models.TextField()),
                ('estado_actual', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En revisión'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('junta_vecinos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_documento', to='organizacion.juntavecinos')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_documento_responsable', to=settings.AUTH_USER_MODEL)),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='solicitudes.tipodocumento')),
                ('vecino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_documento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
