# Generated by Django 5.2.17 on 2026-09-28 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0005_historialsolicituddocumento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudDocumentoArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='solicitudes_documentos/')),
                ('nombre_original', models.CharField(max_length=255)),
                ('tipo_uso', models.CharField(choices=[('ADJUNTO', 'Adjunto'), ('DOCUMENTO_EMITIDO', 'Documento emitido')], default='ADJUNTO', max_length=30)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='solicitudes.solicituddocumento')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archivos_solicitudes_documento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha_subida'],
            },
        ),
    ]
