# Generated by Django 5.2.17 on 2026-09-29 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0006_solicituddocumentoarchivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialSolicitudVecino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('comentario_respuesta', models.TextField(blank=True, default='')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='solicitudes.solicitudvecino')),
                ('usuario_responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_solicitudes_vecino', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha_cambio'],
            },
        ),
    ]
