# Generated by Django 5.2.17 on 2026-09-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0007_historialsolicitudvecino'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicituddocumento',
            name='fecha_ultima_revision_vecino',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudvecino',
            name='fecha_ultima_revision_vecino',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
