# Generated by Django 5.2.17 on 2026-09-26 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacion', '0003_directiva_ck_directiva_fechas_validas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('lugar', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('cupo_maximo', models.PositiveIntegerField(blank=True, help_text='Dejar vacío para un evento sin límite de cupos.', null=True)),
                ('estado', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('CANCELADO', 'Cancelado'), ('FINALIZADO', 'Finalizado')], default='PROGRAMADO', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_creados', to=settings.AUTH_USER_MODEL)),
                ('directiva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='organizacion.directiva')),
            ],
            options={
                'ordering': ['fecha_inicio'],
            },
        ),
    ]
