# Generated by Django 5.2.17 on 2026-09-06 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(blank=True, max_length=255, null=True)),
                ('rut', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True)),
                ('region_id', models.IntegerField(blank=True, null=True)),
                ('comuna_id', models.IntegerField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('jdv', models.IntegerField(blank=True, null=True)),
                ('imagen_1', models.URLField(blank=True, max_length=500, null=True)),
                ('imagen_2', models.URLField(blank=True, max_length=500, null=True)),
                ('imagen_o_doc', models.URLField(blank=True, max_length=500, null=True)),
                ('estado', models.CharField(choices=[('VERIFICACION', 'Esperando verificación'), ('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido'), ('BANEADO', 'Baneado')], default='VERIFICACION', max_length=20)),
                ('cargo_id', models.IntegerField(default=6)),
                ('rol', models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='perfiles', to='profiles.rol')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'ordering': ['nombre_completo'],
            },
        ),
    ]
