# Generated by Django 5.2.17 on 2026-09-22 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_usuario_confirmado_por_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialGestionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cambio', models.CharField(choices=[('CARGO', 'Cargo'), ('ROL', 'Rol'), ('ESTADO_CUENTA', 'Estado de cuenta')], max_length=30)),
                ('valor_anterior', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_nuevo', models.CharField(blank=True, max_length=255, null=True)),
                ('detalle', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('realizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_gestion_realizado', to=settings.AUTH_USER_MODEL)),
                ('usuario_objetivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_gestion_recibido', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_cambio', '-id'],
            },
        ),
    ]
