# Generated by Django 5.2.17 on 2026-10-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_historialgestionusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='estado_asociacion_sector',
            field=models.CharField(blank=True, choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('RECHAZADA', 'Rechazada')], default=None, max_length=20, null=True),
        ),
    ]
