# Generated by Django 5.2.17 on 2026-10-06 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_alter_usuario_estado_asociacion_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaracterizacionComunitaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_personas_hogar', models.PositiveSmallIntegerField()),
                ('cantidad_menores_18', models.PositiveSmallIntegerField(default=0)),
                ('cantidad_adultos_mayores', models.PositiveSmallIntegerField(default=0)),
                ('nivel_educacional', models.CharField(choices=[('SIN_ESTUDIOS', 'Sin estudios formales'), ('BASICA', 'Educación básica'), ('MEDIA', 'Educación media'), ('TECNICO', 'Técnico profesional'), ('SUPERIOR', 'Educación superior'), ('POSTGRADO', 'Postgrado'), ('PREFIERE_NO_RESPONDER', 'Prefiero no responder')], max_length=30)),
                ('situacion_laboral', models.CharField(choices=[('TRABAJANDO', 'Trabajando'), ('ESTUDIANDO', 'Estudiando'), ('DESEMPLEADO', 'Buscando empleo'), ('JUBILADO', 'Jubilado/a'), ('LABORES_HOGAR', 'Labores del hogar'), ('OTRA', 'Otra'), ('PREFIERE_NO_RESPONDER', 'Prefiero no responder')], max_length=30)),
                ('tipo_vivienda', models.CharField(choices=[('CASA', 'Casa'), ('DEPARTAMENTO', 'Departamento'), ('PIEZA', 'Pieza'), ('OTRA', 'Otra'), ('PREFIERE_NO_RESPONDER', 'Prefiero no responder')], max_length=30)),
                ('acceso_internet', models.BooleanField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caracterizacion_comunitaria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caracterización comunitaria',
                'verbose_name_plural': 'Caracterizaciones comunitarias',
            },
        ),
    ]
